sudo: false
language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip3 install -r requirements.txt
  - pip3 install sqlalchemy
  - pip3 install codecov
  - pip3 install pytest-cov
script:
  - pytest --cov=tidyframe
after_success:
  - codecov
